package brdoc

import (
	"testing"
)

func TestIsCNS(t *testing.T) {
	t.Run("rejects invalid data", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"too long", "3467875434578764345789654"},
			{"empty", ""},
			{"letters", "AAAAAAAAAAA"},
		})
	})

	t.Run("rejects invalid formats", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"hyphens", "808-2536-1743-0486"},
			{"spaces in the wrong places", "9999 0236 0200 834"},
		})
	})

	t.Run("rejects invalid check digits", func(t *testing.T) {
		assertInvalid(t, IsCNS,
			"915 5017 0193 0306",
			"174 2241 7133 0004",
			"259 7557 3388 0001",
		)
	})

	t.Run("rejects definitive CNS not generated by the official algorithm", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"suffix 001 instead of 000", "129 1417 7763 0014"},
			{"suffix 001 of a valid CNS", "174 5241 7133 0012"},
		})
	})

	t.Run("accepts valid documents", func(t *testing.T) {
		t.Run("with spaces", func(t *testing.T) {
			assertValid(t, IsCNS,
				"174 5984 3528 0018",
				"259 9557 3388 0001",
				"174 5241 7133 0004",
				"915 5017 0193 0006",
				"750 6557 1844 0005",
				"864 3973 3666 0007",
				"285 0545 6133 0005",
			)
		})

		t.Run("without spaces", func(t *testing.T) {
			assertValid(t, IsCNS,
				"174598435280018",
				"259955733880001",
				"174524171330004",
				"915501701930006",
				"750655718440005",
				"864397336660007",
				"285054561330005",
			)
		})
	})
}
