package brdoc

import (
	"testing"
)

func TestIsCNS(t *testing.T) {
	t.Run("rejects invalid data", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"too long", "3467875434578764345789654"},
			{"empty", ""},
			{"letters", "AAAAAAAAAAA"},
		})
	})

	t.Run("rejects invalid formats", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"hyphens", "712-3456-7890-1236"},
			{"spaces in the wrong places", "7123 4567 8901 236"},
		})
	})

	t.Run("rejects invalid check digits", func(t *testing.T) {
		assertInvalid(t, IsCNS,
			"712 3456 7890 1237",
			"119 7530 8642 0008",
			"139 5061 7284 0019",
		)
	})

	// Calculated by hand, with valid weighted sums.
	t.Run("rejects definitive CNS not generated by the official algorithm", func(t *testing.T) {
		assertInvalidCases(t, IsCNS, []docCase{
			{"suffix 001 instead of 000", "209 8765 4321 0019"},
			{"suffix 001 instead of 000, with another PIS", "119 7530 8642 0015"},
		})
	})

	// Calculated by hand, as real ones are personal data.
	t.Run("accepts valid documents", func(t *testing.T) {
		t.Run("with spaces", func(t *testing.T) {
			assertValid(t, IsCNS,
				"209 8765 4321 0000",
				"119 7530 8642 0007",
				"229 6296 2963 0007",
				"139 5061 7284 0018",
				"249 3827 1605 0018",
				"712 3456 7890 1236",
				"824 6913 5780 2466",
				"937 0370 3670 3691",
			)
		})

		t.Run("without spaces", func(t *testing.T) {
			assertValidCases(t, IsCNS, []docCase{
				{"definitive, suffix 000, check digit 0", "209876543210000"},
				{"definitive, suffix 000, starting with 1", "119753086420007"},
				{"definitive, suffix 000, starting with 2", "229629629630007"},
				{"definitive, suffix 001, starting with 1", "139506172840018"},
				{"definitive, suffix 001, starting with 2", "249382716050018"},
				{"provisional, starting with 7", "712345678901236"},
				{"provisional, starting with 8", "824691357802466"},
				{"provisional, starting with 9", "937037036703691"},
			})
		})
	})
}
