name: CI
on: [push, pull_request]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  gofmt:
    name: Validate gofmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
          cache: false
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
  staticcheck:
    name: Validate staticcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
          cache: false
      - run: "go vet ./..."
      - run: "go install honnef.co/go/tools/cmd/staticcheck@v0.8.1"
      - run: "staticcheck ./..."
  fuzz:
    name: Run fuzz test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: "1.27"
          cache: false
      - run: "go test -run XXX -fuzz FuzzAll -fuzztime 30s ."
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        go: [
          "1.7",
          "1.8",
          "1.9",
          "1.10",
          "1.11",
          "1.12",
          "1.13",
          "1.14",
          "1.15",
          "1.16",
          "1.17",
          "1.18",
          "1.19",
          "1.20",
          "1.21",
          "1.22",
          "1.23",
          "1.24",
          "1.25",
          "1.26",
          "1.27"
        ]
    name: Run tests for Go v${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}
          cache: false
      - run: go test ./...
        if: matrix.os == 'windows-latest'
      - run: go test --race ./...
        if: matrix.os == 'ubuntu-latest'
