name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    container: golang:alpine
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21"
      - run: "go install honnef.co/go/tools/cmd/staticcheck@2022.1.3"
      - run: "staticcheck ./..."